### ISSUE TITLE
The program canno't be moved to somewhere else than C: drive

### ISSUE THREAD

**Issue by Shywizz** [L8X/Roblox-Client-Optimizer#22]
Alright so i don't wanna sound paranoid but this is REALLY sketchy, to actively check if the program is on C:\ root
I don't know if its for just looking in ..\Programs\...etc for roblox, or something, but its definetly not common practice to "_weld_" a program to C:\Drive

**Comment by Kaiddd** [comment]
@Shywizz the program is not welded to the C: drive, rather, the folder is required to exist there, as it is static, you can move the executable wherever you'd like, so long as the folder exists, you do not even need to copy the other files in the folder, so long as they exist in the folder themselves. closing due to being a non-issue, if you still have an issue with this please reply and I may consider making the install path variable, but I do not think it is necessary, also, if you do not trust the program's binary, feel free to audit the C++ code yourself, and build and run it yourself, I encourage you to do so, not only will it build on your programming knowledge, but it will also reassure you of any doubts if you audited and compiled the program yourself!

**Comment by Kaiddd** [comment]
Another note, RCO is not the first program to be installed to C:\. Another great example is Python, unsure if it is every PC, but at least for me, I have "Python310" (Python 3.10) on my C: drive after doing a default installation.

**Comment by Shywizz** [comment]
Thank you for your reply, i didn't know where else to put this so that's why i opened an issue, sorry if that's the wrong place im just a little new to the whole collaborating part

I did know that having something on the C drive isn't harmfull by himself(python was a good example), but it just feels somewhat "_wrong_" to have something sitting there, especially (not again't you, or this little program) some C++ code that im gonna run almost every other day

thank you for making this and for replying to my silly little "issue" and godspeed you legend.
