### ISSUE TITLE
Roblox-Client-Optimizer not uninstalling.

### ISSUE THREAD

**Issue by TheRealKennyMcCormick** [L8X/Roblox-Client-Optimizer#44]
So i tried the program. After i decided its not for me, i tried to uninstall it using RCO2InstallerGUI. Though for some odd reason it isn't uninstalling. help would be much appreciated!

**Comment by Kaiddd** [comment]
@TheRealKennyMcCormick hello! Sorry that RCO wasn't for you.

Can you please closer define not uninstalling for me? Does it not delete the program, or does it not reset the changes to Roblox?

**Comment by TheRealKennyMcCormick** [comment]
It does not reset the changes to roblox, should have been more specific. sorry!

**Comment by Kaiddd** [comment]
@TheRealKennyMcCormick ah yes this is intentional, I'll add a setting to the next installer update to reset the changes too.

For now, go to %localappdata%\Roblox\current-roblox-version\ClientSettings
And delete ClientAppSettings.json

OR

I'd you don't understand the above, an easier method is to simply uninstall Roblox, and then run the below command to be sure the files were cleaned up, and then reinstall

rmdir %localappdata%\Roblox

Let me know if this solves your issue!
Would you also mind sharing any feedback as to why you're removing RCO?

**Comment by TheRealKennyMcCormick** [comment]
That solved the issue. Thanks! Also the reason i was trying to remove RCO is it gives me unstable fps.

Demonstration: i am currently playing any roblox game. I'm at 200 fps. the next second i'm at 10.

By the way thank you for the quick responses!

**Comment by Kaiddd** [comment]
@TheRealKennyMcCormick Happy to help! Sorry that your performance is unstable, hopefully I can resolve this iinconsistency between users when I add settings in 2.1.0

Have a great day!
